In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Declaring a normal python list.

In [2]:
list1 = [1, 2, 3, 4]
type(list1)

list

### Making a numpy array using python lists.

In [3]:
array1 = np.array(list1)
array1

array([1, 2, 3, 4])

In [4]:
type(array1)

numpy.ndarray

### We can also go multi dimensional (in this case 2D)

In [5]:
# Declare an extra list.
list2 = [11, 22, 33, 44]
# Combine the lists into a 2D list.
lists = [list1, list2]
lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [6]:
array2 = np.array(lists)
array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

### just to make sure we can also print the shapes.
We would obviously expect a (4,1) and a (4,2)... or don't we?

In [7]:
print("Arr1: ", array1.shape)
print("Arr2: ", array2.shape)

Arr1:  (4,)
Arr2:  (2, 4)


The best way to think about NumPy arrays is that they consist of two parts, a data buffer which is just a block of raw elements, and a view which describes how to interpret the data buffer.

Here the shape (4,) means the array is indexed by a single index which runs from 0 to 4. 
In most situations the lack of second dimension is not a problem. If it does turn into a problem (e.g. when you are trying to take a transpose of this vector) you can just call the below function to generate a new view:

In [8]:
# Do note the double brackets, as the size is added as a tuple: (rows, columns)
array1 = array1.reshape((4,1))
array1.shape

(4, 1)

Now we happen to know what we stored in our array, but sometimes you do not know such. To ask the data type of your array, you can call:


In [9]:
array2.dtype

dtype('int64')

### Making specific arrays
There are also other ways to make specific arrays, such as:

In [10]:
# The empty array
print("Ex1: ", np.empty(5))

# Array of 5 floating point zeros
print("Ex2: ", np.zeros(5))

# Array of 5 floating point ones
print("Ex3: ", np.ones(5))

# Array of 5 integer incrementing numbers
print("Ex4: ", np.arange(5))

# Start at 5, stop at 20, do it in steps of 2
print("Ex5: ", np.arange(5, 20, 2))

# Making the identity matrix (ones on the diagonal)
print("Ex6: ")
print(np.eye(5))

Ex1:  [ 0.    0.25  0.5   0.75  1.  ]
Ex2:  [ 0.  0.  0.  0.  0.]
Ex3:  [ 1.  1.  1.  1.  1.]
Ex4:  [0 1 2 3 4]
Ex5:  [ 5  7  9 11 13 15 17 19]
Ex6: 
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


### Mathematical operations
You are also able to apply basic mathematical operations to arrays

In [11]:
array3 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])
array3

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [12]:
# Value-wise multiplication
array3 * array3

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [13]:
# Subtraction
array3 - 5

array([[-4, -3, -2, -1],
       [ 3,  4,  5,  6]])

In [14]:
1 / array3

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [15]:
array3 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

#### You can also apply functions to all elements in an array at once.

Some built-in functions of numpy can be found here:
    https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations
        

In [16]:
array4 = np.arange(0, 10)
print(np.sqrt(array4))
print(np.square(array4))

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[ 0  1  4  9 16 25 36 49 64 81]


### Indexing Arrays

In [17]:
array4 = np.arange(0, 10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

There is a minor difference with normal python lists, when it comes to indexing, namely that while the array allows two different ways to call the the value at a position.

In [18]:
list3 = [[1, 2, 3], [4, 5, 6]]
array5 = np.array(list3)

# Watch the brackets closely.
print("List: ", list3[1][2])
# Array can use two different approaches
print("Array ", array5[1, 2])
print("Array ", array5[1][2])

List:  6
Array  6
Array  6


### Slicing arrays
Sometimes you do not want the full array, but just parts of it, we can use array slicing for this

In [19]:
# Show original array
print(array4)
# We want to 2nd to 5th element:
print(array4[2:5])
# We can also use it to set the value of multiple entries:
array4[2:5] = 13
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[ 0  1 13 13 13  5  6  7  8  9]


One important thing to not is that a slice, is just another view of the same data. If you change something in the slice, it also changes in the original. This is nice for you memory efficiency of your program, but sometimes it can hurt you when overlooked.

In [20]:
array4 = np.arange(0, 10)
# Take a slice, consiting of the 2nd to 6th element.
slice_array4 = array4[2:6]
# We iterate over all values, setting them to 22
slice_array4[:] = 22
print(slice_array4)
print(array4)

[22 22 22 22]
[ 0  1 22 22 22 22  6  7  8  9]


To prevent such, we can also make a new copy, to not just generate a view, but to actually reserve new memory for the object we are making

In [ ]:
array4 = np.arange(0, 10)
array5 = array4.copy()
print(array4)
print(array5)
array5[:] = 22
print("So did we make a copy?")
print(array4)
print(array5)
print("Seems we did.")

#### 2D array slicing

In [ ]:
array6 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print(array6)
# let's say you only want just the upper right square of 2x2 of the above matrix
array6[:2, 1:]

#### Fancy Indexing
Sometimes you don't want to have every row, but perhaps skip a few entries. This is easily possible in python. Let us assume we only want the 2nd, 3rd, 5th, and 7th row in the following example.

In [ ]:
# Below we use a list comprehension (which you should have seen in Introduction to Programming as well)
# To generate an array with 10 rows, and each column goes from 0 to 10.
array7 = np.array([[j for i in range(10)] for j in range(10)])
print(array7)
# As we start at index 0, we actually want the following rows [1, 2, 4, 6].
# Also note the double brackets below.
array7[[1, 2, 4, 6]]

You can do the above in any order you wish.

In [ ]:
array7[[7, 3, 5, 2]]

### Array Transposition

In [ ]:
array8 = np.arange(40).reshape((8, 5))
array8

In [ ]:
# If you want to transpose a matrix you can go two ways:
print(np.transpose(array8))
# And
print(array8.T)

### Array Processing

In [ ]:
https://www.udemy.com/learning-python-for-data-analysis-and-visualization/learn/v4/t/lecture/2340122?start=0

In [ ]:
# Range from -5 to 5
points = np.arange(-5, 5, 0.01)

In [ ]:
# Return a meshgrid based on two vectors.

# it generates a len(x) times len(y) matrix.
# This allows you to store the values needed to compare every value of x with every value of y.
# If you input the same vector twice, dy is the transpose of dx
dx, dy = np.meshgrid(points, points)

z = (np.sin(dx) + np.sin(dy))
plt.imshow(z)
plt.colorbar()
plt.title('plot for sin(x) + sin(y)')

#### Numpy Where

In [ ]:
# Numpy Where

A = np.array([1, 2, 3, 4])
B = np.array([100, 200, 300, 400])

condition = np.array([True, True, False, False])

print(A[condition])
print(B[condition])

In [ ]:
# Where my condition is met, choose A, else choose B
answer = [(A_val if cond else B_val) for A_val, B_val, cond in zip(A, B, condition)]
print(answer)

In [ ]:
# Where my condition is met, choose A, else choose B
answer2 = np.where(condition, A, B)
print(answer2)

#### Numpy Any & All

In [ ]:
bool_arr = np.array([True, False, True, True])
# There exist quite useful functions for a concept we call Masking.

In [ ]:
# If any value is true, return true (else false)
bool_arr.any()

In [ ]:
# If all values are true, return true (else false)
bool_arr.all()

#### Numpy Unique and `in` checking

In [ ]:
# Sometimes you just want to know all the unique values in a numpy array, luckily that function was already implemented for you
letters = ['A', 'B', 'C', 'D', 'D', 'A', 'E', 'F', 'G', 'H', 'Z']
np.unique(letters)

In [ ]:
# We can also easily check for a big array, if it exists within a 1D vector.
np.in1d(['X', 'C', 'M', 'Z'], letters)